server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, muy
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
# dubbo 相关配置
dubbo:
  application:
    name: order-provider
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 10000
  protocol:
    # 协议名称
    name: dubbo
    # 协议端口
    port: 20880
  config-center:
    timeout: 10000

